version: "3.7"

services:

  dashboard:
    image: gporras001/dashboard-mysql:v1
    ports:
      - 5000:80
    volumes:
        - ./upload_folder/img:/var/www/html/static/UPLOAD_FOLDER/img
  api:
    image: gporras001/flask-mysql-api:v1
    ports:
      - 5001:5000
    volumes:
        - ./upload_folder/img:/app/static/UPLOAD_FOLDER/img
        - ./upload_folder/video:/app/static/UPLOAD_FOLDER/video
  mysql:
      image: mysql:5.7
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./mysql-data:/var/lib/mysql


